name: Test Disabled Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  testDisabledTests:
    runs-on: ubuntu-latest
    needs: getBuildLists
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust the Python version as needed

      - name: Install dependencies for disabled tests
        run: pip install -r scripts/disabled_tests/requirements.txt

      - name: Run disabled tests scripts
        working-directory: scripts/disabled_tests
        run: |
          python -m unittest discover tests
